# Generated by Django 5.1.3 on 2024-12-04 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaciones', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_texto', models.TextField()),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaciones.asignacionformulario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.pregunta')),
            ],
        ),
    ]
