# Generated by Django 5.1.3 on 2024-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='formulario',
            new_name='grupo',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='opciones',
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo_respuesta',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Sí/No')], max_length=8),
        ),
    ]
